# Generated by Django 4.1.7 on 2023-02-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='clien_price',
            field=models.FloatField(default=0),
        ),
    ]
