# Generated by Django 4.1.7 on 2023-02-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stock_date_remove_stock_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.RemoveField(
            model_name='writeoff',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='writeoff',
            name='item',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='WriteOff',
        ),
    ]
