# Generated by Django 4.1.7 on 2023-02-28 10:53

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_delete_provider_remove_writeoff_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=500)),
                ('adress', models.CharField(max_length=500)),
                ('contact_number', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('Requisites', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
