# Generated by Django 4.1.7 on 2023-02-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.provider'),
            preserve_default=False,
        ),
    ]
