# Generated by Django 4.1.7 on 2023-02-28 10:57

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ESSENCE', models.CharField(choices=[('legal entity', 'Юр.Лицо'), ('Individual entity', 'Физ.Лицо')], max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('adress', models.CharField(max_length=500)),
                ('contact_number', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('Requisites', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
