# Generated by Django 4.1.7 on 2023-02-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(choices=[('write-off', 'Списание'), ('sell', 'Продажа'), ('stocktaking', 'Инвентаризация')], max_length=500)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.stock')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.buyer')),
            ],
        ),
    ]
