# Generated by Django 4.1.7 on 2023-02-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_writeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoff',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
