# Generated by Django 4.1.7 on 2023-02-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_writeoff_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeoff',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
