# Generated by Django 4.1.7 on 2023-02-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_writeoff_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeoff',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
        ),
    ]
