# Generated by Django 4.1.7 on 2023-02-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_writeoff_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.provider'),
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_on_client', models.FloatField(auto_created=True)),
                ('count', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.provider')),
            ],
        ),
    ]
