# Generated by Django 4.1.7 on 2023-02-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_stock_provider_procurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='price_on_client',
            field=models.FloatField(blank=True, editable=False),
        ),
    ]
