# Generated by Django 4.1.7 on 2023-02-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_procurement_price_on_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='price_on_client',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=100),
        ),
    ]
