# Generated by Django 4.1.7 on 2023-02-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_procurement_price_on_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
