# Generated by Django 4.1.7 on 2023-02-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_procurement_user_stock_user_writeoff_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='clien_price',
            new_name='client_price',
        ),
    ]
